import type { Flavor } from '@protomaps/basemaps';

export const EDITORIAL_FLAVOR: Flavor = {
  background: '#f7f6f2',
  earth: '#f7f6f2',
  park_a: '#eaeddf',
  park_b: '#e0e4d4',
  hospital: '#f3eded',
  industrial: '#efefef',
  school: '#f0ede5',
  wood_a: '#e8ebe0',
  wood_b: '#e0e4d6',
  pedestrian: '#f0efeb',
  scrub_a: '#ebeee2',
  scrub_b: '#e4e8db',
  glacier: '#e7eef3',
  sand: '#f2efe0',
  beach: '#f0edd6',
  aerodrome: '#ececec',
  runway: '#e0e0e0',
  water: '#d2e2ee',
  zoo: '#e8ebe0',
  military: '#ececec',

  tunnel_other_casing: '#e0e0e0',
  tunnel_minor_casing: '#e0e0e0',
  tunnel_link_casing: '#e0e0e0',
  tunnel_major_casing: '#e0e0e0',
  tunnel_highway_casing: '#e0e0e0',
  tunnel_other: '#f0efeb',
  tunnel_minor: '#f0efeb',
  tunnel_link: '#f0efeb',
  tunnel_major: '#f0efeb',
  tunnel_highway: '#f0efeb',

  pier: '#e8e5de',
  buildings: '#e8e5de',

  minor_service_casing: '#e8e5de',
  minor_casing: '#e8e5de',
  link_casing: '#e8e5de',
  major_casing_late: '#e0ddd6',
  highway_casing_late: '#d6d3cc',
  other: '#f0efeb',
  minor_service: '#f0efeb',
  minor_a: '#ffffff',
  minor_b: '#ffffff',
  link: '#ffffff',
  major_casing_early: '#e0ddd6',
  major: '#ffffff',
  highway_casing_early: '#d6d3cc',
  highway: '#ffffff',
  railway: '#d1d1d1',

  boundaries: '#8c8c8c',

  bridges_other_casing: '#e0ddd6',
  bridges_minor_casing: '#e0ddd6',
  bridges_link_casing: '#e0ddd6',
  bridges_major_casing: '#d6d3cc',
  bridges_highway_casing: '#d6d3cc',
  bridges_other: '#f0efeb',
  bridges_minor: '#ffffff',
  bridges_link: '#ffffff',
  bridges_major: '#ffffff',
  bridges_highway: '#ffffff',

  roads_label_minor: '#6b6b6b',
  roads_label_minor_halo: '#f7f6f2',
  roads_label_major: '#4a4a4a',
  roads_label_major_halo: '#f7f6f2',

  ocean_label: '#7a9ab5',
  subplace_label: '#8a8a8a',
  subplace_label_halo: '#f7f6f2',
  city_label: '#333333',
  city_label_halo: '#f7f6f2',
  state_label: '#8c8c8c',
  state_label_halo: '#f7f6f2',
  country_label: '#555555',

  address_label: '#999999',
  address_label_halo: '#f7f6f2',

  regular: 'Noto Sans Regular',
  bold: 'Noto Sans Bold',
  italic: 'Noto Sans Italic',

  landcover: {
    barren: '#e8e5de',
    farmland: '#eef0e4',
    forest: '#dce3d4',
    glacier: '#e7eef3',
    grassland: '#e4e8da',
    scrub: '#e2e6d8',
    urban_area: '#ececec',
  },
};
